version: 2
updates:
  - package-ecosystem: maven
    directory: /backend-core
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Ho_Chi_Minh
    groups:
      backend-minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /frontend-portal
    schedule:
      interval: weekly
      day: monday
      time: "02:15"
      timezone: Asia/Ho_Chi_Minh
    groups:
      frontend-minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:30"
      timezone: Asia/Ho_Chi_Minh
    groups:
      actions:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /infra/docker
    schedule:
      interval: weekly
      day: monday
      time: "02:45"
      timezone: Asia/Ho_Chi_Minh
    groups:
      runtime-images:
        patterns: ["*"]
    open-pull-requests-limit: 5
