services:
  postgres:
    image: postgres:16-alpine
    container_name: payment-gateway-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: payment_gateway
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateway_user -d payment_gateway"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: payment-gateway-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: payment-gateway-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: gateway_user
      RABBITMQ_DEFAULT_PASS: gateway_pass
    ports:
      - "5672:5672"     # AMQP protocol
      - "15672:15672"   # RabbitMQ Web Management Dashboard
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  pgdata:
  redisdata:
  rabbitmqdata:
