'use client';

import { Check, Landmark, Plus, RefreshCw, Star, Trash2 } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { BankLogo } from '@/components/BankLogos';
import styles from '../portal-management.module.css';

type Bank = { id:string; bankCode:string; accountNumberMasked:string; accountName:string; accountType:string; connectionMode:string; status:string; defaultAccount:boolean; lastSyncedAt?:string; createdAt:string };
const BANKS = ['ACB','BIDV','VIETINBANK','NCB','VCB','TCB','MB','VPB','TPB','VIB','STB','OCB','MSB','SHBVN','COOPBANK'];

export default function BanksPage() {
  const [items,setItems]=useState<Bank[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(''); const [notice,setNotice]=useState(''); const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);const response=await fetch('/api/gateway/v1/bank_accounts',{cache:'no-store'});if(response.ok)setItems(await response.json());else setError('Không tải được danh sách ngân hàng.');setLoading(false)},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const mutate=async(id:string,action:'default'|'sync'|'delete')=>{setBusy(id+action);setError('');const response=await fetch(`/api/gateway/v1/bank_accounts/${id}${action==='delete'?'':`/${action}`}`,{method:action==='delete'?'DELETE':'POST'});if(response.ok){setNotice(action==='delete'?'Đã ngắt kết nối tài khoản.':action==='default'?'Đã đặt tài khoản mặc định.':'Đồng bộ tài khoản thành công.');await load()}else setError((await response.json().catch(()=>null))?.message||'Thao tác chưa thành công.');setBusy('')};
  const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy('create');setError('');const data=new FormData(event.currentTarget);const response=await fetch('/api/gateway/v1/bank_accounts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({bankCode:data.get('bankCode'),accountNumber:data.get('accountNumber'),accountName:data.get('accountName'),accountType:'BUSINESS',defaultAccount:data.get('defaultAccount')==='on'})});if(response.ok){event.currentTarget.reset();setNotice('Đã thêm tài khoản ngân hàng sandbox.');await load()}else setError((await response.json().catch(()=>null))?.message||'Không thể thêm tài khoản.');setBusy('')};
  const active=items.filter(item=>item.status==='ACTIVE');
  return <div className={styles.page}><header className={styles.head}><div><span className={styles.eyebrow}>BANK HUB</span><h1>Ngân hàng nhận tiền</h1><p>Quản lý tài khoản VietQR, trạng thái kết nối và tài khoản nhận tiền mặc định.</p></div><button className={styles.secondary} onClick={()=>void load()}><RefreshCw size={15}/>Làm mới</button></header>
    {(notice||error)&&<div className={styles.notice} data-error={Boolean(error)}><span>{error||notice}</span><button onClick={()=>{setNotice('');setError('')}}>Đóng</button></div>}
    <section className={styles.stats}><div className={styles.stat}><span>Tài khoản đang hoạt động</span><b>{active.length}</b></div><div className={styles.stat}><span>Ngân hàng hỗ trợ</span><b>{BANKS.length}</b></div><div className={styles.stat}><span>Tài khoản mặc định</span><b>{items.find(item=>item.defaultAccount)?.bankCode||'—'}</b></div><div className={styles.stat}><span>Chế độ</span><b>Sandbox</b></div></section>
    <div className={styles.grid}><section className={styles.card}><div className={styles.cardHead}><h2>Tài khoản đã kết nối</h2><span>{loading?'Đang tải…':`${items.length} tài khoản`}</span></div><div className={styles.bankList}>{!loading&&items.length===0?<div className={styles.empty}><Landmark/><b>Chưa có tài khoản</b><span>Thêm tài khoản sandbox để tạo VietQR.</span></div>:items.map(item=><article className={styles.bank} key={item.id}><BankLogo code={item.bankCode} size={38}/><div className={styles.bankCopy}><b>{item.bankCode} · {item.accountNumberMasked}</b><span>{item.accountName} · {item.connectionMode}{item.lastSyncedAt?` · ${new Date(item.lastSyncedAt).toLocaleString('vi-VN')}`:''}</span></div><div className={styles.chips}>{item.defaultAccount&&<span className={styles.chip}><Star size={10}/> Mặc định</span>}<span className={styles.chip} data-tone={item.status==='ACTIVE'?'':'muted'}>{item.status}</span><button className={styles.iconAction} disabled={busy.startsWith(item.id)} onClick={()=>void mutate(item.id,'sync')} title="Đồng bộ"><RefreshCw size={14}/></button>{!item.defaultAccount&&item.status==='ACTIVE'&&<button className={styles.iconAction} disabled={busy.startsWith(item.id)} onClick={()=>void mutate(item.id,'default')} title="Đặt mặc định"><Check size={14}/></button>}<button className={styles.iconAction} disabled={busy.startsWith(item.id)} onClick={()=>void mutate(item.id,'delete')} title="Ngắt kết nối"><Trash2 size={14}/></button></div></article>)}</div></section>
      <section className={styles.card}><div className={styles.cardHead}><h2>Thêm tài khoản</h2><Plus size={17}/></div><form className={styles.form} onSubmit={create}><div className={styles.field}><label>Ngân hàng</label><select name="bankCode" required>{BANKS.map(code=><option key={code}>{code}</option>)}</select></div><div className={styles.field}><label>Số tài khoản</label><input name="accountNumber" required minLength={6} maxLength={30} placeholder="24550721"/></div><div className={styles.field}><label>Tên chủ tài khoản</label><input name="accountName" required minLength={3} placeholder="CONG TY API PAY"/></div><label className={styles.checkbox}><input type="checkbox" name="defaultAccount"/> Dùng làm tài khoản nhận tiền mặc định</label><button className={styles.primary} disabled={busy==='create'}><Plus size={15}/>{busy==='create'?'Đang thêm…':'Thêm tài khoản sandbox'}</button></form></section></div></div>;
}
