'use client';

import { Check, Download, ReceiptText } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { PortalSkeleton } from '@/components/PortalFeedback';
import styles from '../portal-management.module.css';

type Plan={code:string;displayName:string;monthlyPrice:number;monthlyPaymentLimit:number;bankAccountLimit:number;webhookEndpointLimit:number;retentionDays:number};
type Subscription={plan:string;plan_name:string;status:string;monthly_price:number;payment_usage:number;payment_limit:number;bank_account_usage:number;bank_account_limit:number;webhook_endpoint_usage:number;webhook_endpoint_limit:number;period_end:string};
type Invoice={id:string;invoiceNumber:string;periodStart:string;periodEnd:string;planCode:string;total:number;currency:string;status:string;issuedAt:string};
type Event={id:string;previousPlan?:string;newPlan:string;reason:string;createdAt:string};
const money=new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0});

export default function BillingPage(){const [plans,setPlans]=useState<Plan[]>([]);const [subscription,setSubscription]=useState<Subscription|null>(null);const [invoices,setInvoices]=useState<Invoice[]>([]);const [events,setEvents]=useState<Event[]>([]);const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [canChange,setCanChange]=useState(false);
  const load=useCallback(async()=>{setError('');try{const [responses,sessionResponse]=await Promise.all([Promise.all(['/api/gateway/v1/organization/plans','/api/gateway/v1/organization/subscription','/api/gateway/v1/billing/invoices','/api/gateway/v1/billing/subscription-events'].map(url=>fetch(url,{cache:'no-store'}))),fetch('/api/auth/session',{cache:'no-store'})]);if(!responses.every(item=>item.ok))throw new Error('billing');setPlans(await responses[0].json());setSubscription(await responses[1].json());setInvoices(await responses[2].json());setEvents(await responses[3].json());if(sessionResponse.ok){const session=await sessionResponse.json();setCanChange(session?.session?.role==='OWNER')}}catch{setError('Không thể tải đầy đủ dữ liệu hóa đơn. Vui lòng thử lại.')}finally{setLoading(false)}},[]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const choose=async(code:string)=>{if(code===subscription?.plan||!canChange)return;setBusy(code);const response=await fetch('/api/gateway/v1/organization/subscription',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({plan:code})});if(response.ok){setNotice(`Đã chuyển sang gói ${code}.`);await load()}else setNotice('Không thể thay đổi gói lúc này.');setBusy('')};
  const quota=subscription?Math.min(100,Math.round(subscription.payment_usage/Math.max(1,subscription.payment_limit)*100)):0;
  return <div className={styles.page}><header className={styles.head}><div><span className={styles.eyebrow}>SUBSCRIPTION & BILLING</span><h1>Gói dịch vụ và hóa đơn</h1><p>Theo dõi hạn mức, lịch sử thay đổi và tải chứng từ thanh toán.</p></div></header>{(notice||error)&&<div className={styles.notice} data-error={Boolean(error)}><span>{error||notice}</span><button onClick={()=>{setNotice('');setError('')}}>Đóng</button></div>}{loading&&<PortalSkeleton rows={5}/>} {!loading&&<>
    <section className={styles.stats}><div className={styles.stat}><span>Gói hiện tại</span><b>{subscription?.plan||'—'}</b></div><div className={styles.stat}><span>Chi phí tháng</span><b>{money.format(subscription?.monthly_price||0)}</b></div><div className={styles.stat}><span>Giao dịch đã dùng</span><b>{subscription?.payment_usage||0}</b></div><div className={styles.stat}><span>Ngày gia hạn</span><b>{subscription?.period_end?new Date(subscription.period_end).toLocaleDateString('vi-VN'):'—'}</b></div></section>
    <div className={styles.usage}><div><span>Hạn mức giao dịch</span><b>{subscription?.payment_usage||0} / {subscription?.payment_limit||0}</b></div><i><b style={{width:`${quota}%`}}/></i></div>
    <section className={styles.plans}>{plans.map(plan=><article className={`${styles.card} ${styles.plan}`} data-active={plan.code===subscription?.plan} key={plan.code}><div className={styles.cardHead}><h2>{plan.displayName}</h2>{plan.code===subscription?.plan&&<span className={styles.chip}>Đang dùng</span>}</div><div className={styles.price}>{money.format(plan.monthlyPrice)} <small>/ tháng</small></div><div className={styles.feature}><Check size={14}/>{plan.monthlyPaymentLimit.toLocaleString('vi-VN')} giao dịch/tháng</div><div className={styles.feature}><Check size={14}/>{plan.bankAccountLimit} tài khoản ngân hàng</div><div className={styles.feature}><Check size={14}/>{plan.webhookEndpointLimit} webhook endpoints</div><div className={styles.feature}><Check size={14}/>Lưu dữ liệu {plan.retentionDays} ngày</div><button className={plan.code===subscription?.plan?styles.secondary:styles.primary} disabled={!canChange||plan.code===subscription?.plan||busy!==''} onClick={()=>void choose(plan.code)}>{busy===plan.code?'Đang cập nhật…':plan.code===subscription?.plan?'Gói hiện tại':canChange?'Chọn gói':'Chỉ Owner được đổi gói'}</button></article>)}</section>
    <div className={styles.grid}><section className={styles.card}><div className={styles.cardHead}><h2>Hóa đơn</h2><ReceiptText size={17}/></div><div className={styles.table}><table><thead><tr><th>MÃ HÓA ĐƠN</th><th>CHU KỲ</th><th>GÓI</th><th>TỔNG TIỀN</th><th>TRẠNG THÁI</th><th></th></tr></thead><tbody>{invoices.map(invoice=><tr key={invoice.id}><td><b>{invoice.invoiceNumber}</b></td><td>{new Date(invoice.periodStart).toLocaleDateString('vi-VN')} – {new Date(invoice.periodEnd).toLocaleDateString('vi-VN')}</td><td>{invoice.planCode}</td><td>{money.format(invoice.total)}</td><td><span className={styles.status}>{invoice.status}</span></td><td><a className={styles.iconAction} href={`/api/gateway/v1/billing/invoices/${invoice.id}.csv`} title="Tải CSV"><Download size={14}/></a></td></tr>)}</tbody></table></div></section><section className={styles.card}><div className={styles.cardHead}><h2>Lịch sử gói</h2><span>{events.length} sự kiện</span></div><div className={styles.history}>{events.map(event=><div className={styles.historyItem} key={event.id}><div><b>{event.previousPlan||'Khởi tạo'} → {event.newPlan}</b><small>{event.reason} · {new Date(event.createdAt).toLocaleString('vi-VN')}</small></div></div>)}</div></section></div></>}</div>}
