'use client';

import Link from 'next/link';
import { ArrowLeft, Ban, CheckCircle2, CreditCard, Play, RefreshCw, RotateCcw, ShieldCheck, Undo2 } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { PortalEmpty, PortalSkeleton, PortalToast } from '@/components/PortalFeedback';
import styles from './acquirer.module.css';

type Intent = { id: string; amount: number; currency: string; description?: string; status: string; createdAt: string };
type Operation = { id: string; paymentIntentId: string; parentOperationId?: string; operationType: string; processorReference: string; amount: number; currency: string; status: string; threeDsVersion?: string; actionUrl?: string; failureCode?: string; createdAt: string };
type HostedConfig = { mode: string; tokenizationEndpoint: string; allowedFields: string[]; rawCardDataMustNotReachMerchantServer: boolean; threeDsVersions: string[] };
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`/api/gateway/${path}`, { cache: 'no-store', ...init }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload?.error?.message || payload?.message || `HTTP ${response.status}`); return payload as T; }
const money = (value: number) => new Intl.NumberFormat('vi-VN').format(value) + ' ₫';

export default function AcquirerPage() {
  const [intents, setIntents] = useState<Intent[]>([]); const [intentId, setIntentId] = useState(''); const [operations, setOperations] = useState<Operation[]>([]); const [config, setConfig] = useState<HostedConfig | null>(null); const [amount, setAmount] = useState(100000); const [scenario, setScenario] = useState('success'); const [require3ds, setRequire3ds] = useState(true); const [loading, setLoading] = useState(true); const [toast, setToast] = useState<{ message: string; tone?: 'success' | 'error' } | null>(null);
  const loadOperations = useCallback(async (selected: string) => { if (!selected) { setOperations([]); return; } setOperations(await api<Operation[]>(`v1/acquirer/operations?paymentIntentId=${encodeURIComponent(selected)}`)); }, []);
  const refresh = useCallback(async () => { try { const [intentData, hosted] = await Promise.all([api<Intent[]>('v1/payment_intents?limit=50'), api<HostedConfig>('v1/acquirer/hosted-fields/config')]); setIntents(intentData); setConfig(hosted); const selected = intentId || intentData[0]?.id || ''; setIntentId(selected); await loadOperations(selected); } catch (error) { setToast({ message: String(error), tone: 'error' }); } finally { setLoading(false); } }, [intentId, loadOperations]);
  useEffect(() => { const timer = setTimeout(() => void refresh(), 0); return () => clearTimeout(timer); }, [refresh]);
  const execute = async (operationType: string, parent?: Operation, overrideAmount?: number) => { try { await api<Operation>('v1/acquirer/operations', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify({ paymentIntentId: parent ? undefined : intentId, parentOperationId: parent?.id, operationType, amount: overrideAmount || (parent ? parent.amount : amount), currency: parent?.currency || 'VND', scenario, requestThreeDs: operationType === 'AUTHORIZE' && require3ds }) }); setToast({ message: `Đã chạy ${operationType} sandbox.` }); await loadOperations(intentId); } catch (error) { setToast({ message: String(error), tone: 'error' }); } };
  const complete3ds = async (operation: Operation) => { try { await api(`v1/acquirer/operations/${operation.id}/3ds`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ successful: true }) }); setToast({ message: '3DS sandbox đã xác thực.' }); await loadOperations(intentId); } catch (error) { setToast({ message: String(error), tone: 'error' }); } };
  const selectedIntent = intents.find((item) => item.id === intentId);
  return <main className={styles.shell}><Link className={styles.back} href="/dashboard"><ArrowLeft size={16} /> Merchant Dashboard</Link><header className={styles.header}><div><span>ACQUIRER SANDBOX</span><h1>Card lifecycle playground</h1><p>Thử authorize, 3DS, capture, void, refund và dispute mà không gửi dữ liệu thẻ thật.</p></div><button className="btn-glass" onClick={() => void refresh()}><RefreshCw size={16} /> Làm mới</button></header>
    <section className={styles.security}><ShieldCheck size={22} /><div><b>Hosted Fields contract</b><small>{config?.rawCardDataMustNotReachMerchantServer ? 'PAN/CVC không được đi qua merchant server' : 'Đang tải cấu hình…'}</small></div><code>{config?.tokenizationEndpoint}</code><span>3DS {config?.threeDsVersions.join(' / ')}</span></section>
    <div className={styles.grid}><section className={styles.card}><h2><CreditCard size={19} /> Bắt đầu authorization</h2>{loading ? <PortalSkeleton /> : <div className={styles.form}><label>Payment Intent<select value={intentId} onChange={(event) => { setIntentId(event.target.value); void loadOperations(event.target.value); }}><option value="">Chọn giao dịch</option>{intents.map((intent) => <option value={intent.id} key={intent.id}>{money(intent.amount)} · {intent.description || intent.id}</option>)}</select></label><label>Số tiền<input type="number" min={1} value={amount} onChange={(event) => setAmount(Number(event.target.value))} /></label><label>Kịch bản<select value={scenario} onChange={(event) => setScenario(event.target.value)}><option value="success">Thành công</option><option value="declined">Từ chối</option></select></label><label className={styles.checkbox}><input type="checkbox" checked={require3ds} onChange={(event) => setRequire3ds(event.target.checked)} /> Yêu cầu 3DS 2.2</label><button className="btn-adyen-green" disabled={!intentId} onClick={() => void execute('AUTHORIZE')}><Play size={15} /> Authorize</button></div>} {selectedIntent && <div className={styles.intent}><small>INTENT ĐANG CHỌN</small><b>{money(selectedIntent.amount)}</b><span>{selectedIntent.status}</span><code>{selectedIntent.id}</code></div>}</section>
      <section className={styles.card}><h2>Operation timeline</h2>{loading ? <PortalSkeleton rows={4} /> : operations.length === 0 ? <PortalEmpty title="Chưa có acquirer operation" description="Chọn Payment Intent và chạy authorization đầu tiên." /> : <div className={styles.timeline}>{operations.map((operation) => <article key={operation.id}><i data-status={operation.status}>{operation.status === 'FAILED' ? <Ban size={15} /> : <CheckCircle2 size={15} />}</i><div><header><b>{operation.operationType}</b><span data-status={operation.status}>{operation.status}</span></header><strong>{money(operation.amount)}</strong><code>{operation.processorReference}</code>{operation.failureCode && <small>{operation.failureCode}</small>}<footer>{operation.status === 'REQUIRES_ACTION' && <button onClick={() => void complete3ds(operation)}><ShieldCheck size={14} /> Complete 3DS</button>}{operation.status === 'AUTHORIZED' && <><button onClick={() => void execute('CAPTURE', operation)}><CheckCircle2 size={14} /> Capture</button><button onClick={() => void execute('VOID', operation)}><Ban size={14} /> Void</button></>}{operation.status === 'CAPTURED' && <><button onClick={() => void execute('REFUND', operation, Math.max(1, Math.floor(operation.amount / 2)))}><Undo2 size={14} /> Refund 50%</button><button onClick={() => void execute('DISPUTE', operation)}><RotateCcw size={14} /> Dispute</button></>}</footer></div></article>)}</div>}</section></div>{toast && <PortalToast message={toast.message} tone={toast.tone} onClose={() => setToast(null)} />}</main>;
}
