'use client';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowLeft, ExternalLink } from 'lucide-react';
import { useEffect, useState } from 'react';
import { BankLogo } from '@/components/BankLogos';
import { PortalSkeleton } from '@/components/PortalFeedback';
import styles from '../../financial-detail.module.css';
type Item={id:string;slug:string;paymentCode:string;amount:number;currency:string;description:string;status:string;bankCode:string;bankName:string;accountNumber:string;accountName:string;qrPayload:string;expiresAt:string;paidAt?:string};
export default function PaymentLinkDetail({id}:{id:string}){const[item,setItem]=useState<Item|null>(null);const[error,setError]=useState('');useEffect(()=>{fetch(`/api/gateway/v1/payment_links/${id}`,{cache:'no-store'}).then(async response=>{if(!response.ok)throw new Error(`HTTP ${response.status}`);setItem(await response.json());}).catch(reason=>setError(String(reason)));},[id]);if(error)return <main className={styles.shell}><p>{error}</p></main>;if(!item)return <main className={styles.shell}><PortalSkeleton rows={5}/></main>;return <main className={styles.shell}><Link className={styles.back} href="/payment-links"><ArrowLeft size={16}/> Payment Links</Link><section className={styles.hero}><div><small>PAYMENT LINK</small><h1>{item.description}</h1><span className={styles.status}>{item.status}</span></div><div><small>TỔNG TIỀN</small><strong>{new Intl.NumberFormat('vi-VN').format(item.amount)} ₫</strong></div></section><div className={styles.grid}><section className={styles.card}><h2>Thông tin thanh toán</h2><div className={styles.rows}><div><span>Mã thanh toán</span><b>{item.paymentCode}</b></div><div><span>Ngân hàng</span><b title={item.bankName}><BankLogo code={item.bankCode} size={27}/></b></div><div><span>Số tài khoản</span><b>{item.accountNumber}</b></div><div><span>Chủ tài khoản</span><b>{item.accountName}</b></div><div><span>Hết hạn</span><b>{new Date(item.expiresAt).toLocaleString('vi-VN')}</b></div><div><span>Thanh toán lúc</span><b>{item.paidAt?new Date(item.paidAt).toLocaleString('vi-VN'):'—'}</b></div></div><div className={styles.actions}><Link className="btn-adyen-green" target="_blank" href={`/pay/${item.slug}`}>Mở trang thanh toán <ExternalLink size={15}/></Link></div></section><section className={styles.card}><h2>VietQR</h2><Image unoptimized src={`/api/gateway/v1/payment_links/public/${item.slug}/qr.svg?size=280`} width={240} height={240} alt="VietQR"/><pre className={styles.payload}>{item.qrPayload}</pre></section></div></main>}
