'use client';

import { Download, Search, ShieldCheck } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { PortalSkeleton } from '@/components/PortalFeedback';
import styles from '../portal-management.module.css';

type Audit={id:string;actorType:string;actorId:string;action:string;resourceType:string;resourceId?:string;requestId?:string;ipAddress?:string;details?:string;createdAt:string};
export default function AuditLogsPage(){const [items,setItems]=useState<Audit[]>([]);const [query,setQuery]=useState('');const [action,setAction]=useState('');const [resource,setResource]=useState('');const [selected,setSelected]=useState<Audit|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=useCallback(async()=>{try{const response=await fetch('/api/gateway/v1/audit_logs?limit=250',{cache:'no-store'});if(!response.ok)throw new Error('audit');setItems(await response.json())}catch{setError('Không thể tải nhật ký kiểm toán.')}finally{setLoading(false)}},[]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const actions=useMemo(()=>[...new Set(items.map(item=>item.action))].sort(),[items]);const resources=useMemo(()=>[...new Set(items.map(item=>item.resourceType))].sort(),[items]);const filtered=items.filter(item=>(!action||item.action===action)&&(!resource||item.resourceType===resource)&&(!query||`${item.actorId} ${item.action} ${item.resourceType} ${item.resourceId||''} ${item.requestId||''}`.toLowerCase().includes(query.toLowerCase())));
 return <div className={styles.page}><header className={styles.head}><div><span className={styles.eyebrow}>COMPLIANCE & SECURITY</span><h1>Nhật ký kiểm toán</h1><p>Dòng thời gian bất biến cho thay đổi cấu hình và hoạt động tài chính.</p></div><a className={styles.secondary} href="/api/gateway/v1/audit_logs/export.csv"><Download size={15}/>Xuất CSV</a></header>{error&&<div className={styles.notice} data-error="true">{error}</div>}{loading?<PortalSkeleton rows={6}/>:<>
 <section className={styles.stats}><div className={styles.stat}><span>Tổng sự kiện hiển thị</span><b>{items.length}</b></div><div className={styles.stat}><span>Nhóm hành động</span><b>{actions.length}</b></div><div className={styles.stat}><span>Loại tài nguyên</span><b>{resources.length}</b></div><div className={styles.stat}><span>Chế độ ghi</span><b>Append-only</b></div></section>
 <section className={styles.card}><div className={styles.filter}><div className={styles.field}><div style={{position:'relative'}}><Search size={15} style={{position:'absolute',left:12,top:12}}/><input style={{paddingLeft:36}} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Tìm actor, request ID, resource…"/></div></div><select value={action} onChange={event=>setAction(event.target.value)}><option value="">Mọi hành động</option>{actions.map(value=><option key={value}>{value}</option>)}</select><select value={resource} onChange={event=>setResource(event.target.value)}><option value="">Mọi tài nguyên</option>{resources.map(value=><option key={value}>{value}</option>)}</select><button className={styles.secondary} onClick={()=>{setQuery('');setAction('');setResource('')}}>Xóa bộ lọc</button></div>
 <div className={styles.table}><table><thead><tr><th>THỜI GIAN</th><th>ACTOR</th><th>HÀNH ĐỘNG</th><th>TÀI NGUYÊN</th><th>REQUEST ID</th></tr></thead><tbody>{filtered.map(item=><tr className={styles.auditRow} key={item.id} onClick={()=>setSelected(item)}><td>{new Date(item.createdAt).toLocaleString('vi-VN')}</td><td><b>{item.actorType}</b><div className={styles.code}>{item.actorId.slice(0,18)}</div></td><td><span className={styles.status}>{item.action}</span></td><td>{item.resourceType}<div className={styles.code}>{item.resourceId||'—'}</div></td><td className={styles.code}>{item.requestId||'—'}</td></tr>)}</tbody></table></div>{filtered.length===0&&<div className={styles.empty}><ShieldCheck/><b>Không có sự kiện phù hợp</b><span>Thử thay đổi bộ lọc tìm kiếm.</span></div>}
 {selected&&<div className={styles.detail}><div className={styles.cardHead}><h2>Chi tiết sự kiện</h2><button onClick={()=>setSelected(null)}>Đóng</button></div><pre>{JSON.stringify({...selected,details:parseDetails(selected.details)},null,2)}</pre></div>}</section></>}</div>}

function parseDetails(details?:string){if(!details)return null;try{return JSON.parse(details)}catch{return details}}
